import { redirect } from "react-router";
import styles from "./styles.module.css";

export const loader = async ({ request }) => {
  const url = new URL(request.url);

  if (url.searchParams.get("shop")) {
    throw redirect(`/app?${url.searchParams.toString()}`);
  }

  return null;
};

export default function App() {
  return (
    <div className={styles.index}>
      <div className={styles.content}>
        <h1 className={styles.heading}>Tagioo Tracking for Shopify</h1>
        <p className={styles.text}>
          Connect your Shopify store to Tagioo for server-side ecommerce tracking.
        </p>
        <p className={styles.text}>Install and open the app from your Shopify admin, then enter the one-time connection code generated by Tagioo.</p>
        <ul className={styles.list}>
          <li>
            <strong>Track the storefront.</strong> Send page, product, cart and checkout events through your Tagioo server container.
          </li>
          <li>
            <strong>Recover purchases.</strong> Use signed Shopify webhooks for reliable paid-order tracking.
          </li>
          <li>
            <strong>Measure performance.</strong> Forward ecommerce events to your configured analytics destinations.
          </li>
        </ul>
      </div>
    </div>
  );
}
